version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' #bin/docker-rails-start #
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:12201'
    depends_on:
      - db

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201/udp"

  elasticsearch:
    image: elasticsearch:5.6.14
    command: elasticsearch -Enetwork.host=0.0.0.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /usr/share/elasticsearch/data

  kibana:
    build: kibana/
    ports:
      - "5601:5601"
